"""create hideout progress

Revision ID: 744ba532fb02
Revises: a53fd9162d0c
Create Date: 2026-04-30 13:04:37.852783

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '744ba532fb02'
down_revision: Union[str, Sequence[str], None] = 'a53fd9162d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hideout_progress',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('module_id', sa.String(), nullable=False),
                    sa.Column('current_level', sa.Integer(), nullable=False),
                    sa.Column('level_progress', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('hideout_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hideout_progress_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hideout_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_social_links', schema=None) as batch_op:
        batch_op.alter_column('provider',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.alter_column('access_token',
                              existing_type=sa.VARCHAR(),
                              nullable=False)
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=True,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_user_social_links_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('provider',
                              existing_type=sa.VARCHAR(),
                              nullable=True,
                              existing_server_default=sa.text("'local'"))
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=True,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=False,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('provider',
                              existing_type=sa.VARCHAR(),
                              nullable=False,
                              existing_server_default=sa.text("'local'"))

    with op.batch_alter_table('user_social_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_social_links_user_id'))
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=False,
                              existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('access_token',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.alter_column('provider',
                              existing_type=sa.VARCHAR(),
                              nullable=False)

    with op.batch_alter_table('hideout_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hideout_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_hideout_progress_module_id'))

    op.drop_table('hideout_progress')
    # ### end Alembic commands ###
